/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatWindow: typeof import('./../../components/layouts/ai-chat-window/index.vue')['default']
    ButtonTable: typeof import('./../../components/forms/button-table/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GlobalComponent: typeof import('./../../components/layouts/global-component/index.vue')['default']
    HeaderBar: typeof import('./../../components/layouts/header-bar/index.vue')['default']
    IconButton: typeof import('./../../components/widget/icon-button/index.vue')['default']
    Logo: typeof import('./../../components/base/logo/index.vue')['default']
    MdEditor: typeof import('./../../components/MdEditor.vue')['default']
    MixedMenu: typeof import('./../../components/layouts/menus/mixed-menu/index.vue')['default']
    PageContent: typeof import('./../../components/layouts/page-content/index.vue')['default']
    RingChart: typeof import('./../../components/charts/ring-chart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../../components/forms/search-bar/index.vue')['default']
    SidebarMenu: typeof import('./../../components/layouts/menus/sidebar-menu/index.vue')['default']
    SidebarSubmenu: typeof import('./../../components/layouts/menus/sidebar-menu/widget/SidebarSubmenu.vue')['default']
    SvgIcon: typeof import('./../../components/base/svg-icon/index.vue')['default']
    Table: typeof import('./../../components/tables/table/index.vue')['default']
    TableHeader: typeof import('./../../components/tables/table-header/index.vue')['default']
    UserMenu: typeof import('./../../components/layouts/header-bar/widget/UserMenu.vue')['default']
    WangEditor: typeof import('./../../components/forms/wang-editor/index.vue')['default']
    WojCodeEditor: typeof import('./../../components/WojCodeEditor.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
